\include "bwv-846-prelude-and-fugue-1/prelude/score.ly"
\include "bwv-846-prelude-and-fugue-1/fugue/score.ly"
\include "bwv-847-prelude-and-fugue-2/prelude/score.ly"
\include "bwv-847-prelude-and-fugue-2/fugue/score.ly"
\include "bwv-848-prelude-and-fugue-3/prelude/score.ly"
\include "bwv-848-prelude-and-fugue-3/fugue/score.ly"
% \include "bwv-849-prelude-and-fugue-4/prelude/score.ly"
% \include "bwv-849-prelude-and-fugue-4/fugue/score.ly"
% \include "bwv-850-prelude-and-fugue-5/prelude/score.ly"
% \include "bwv-850-prelude-and-fugue-5/fugue/score.ly"
% \include "bwv-851-prelude-and-fugue-6/prelude/score.ly"
% \include "bwv-851-prelude-and-fugue-6/fugue/score.ly"
\include "bwv-852-prelude-and-fugue-7/prelude/score.ly"
